### ISSUE TITLE
different results

### ISSUE THREAD

**Issue by albertotono** [nikitakaraevv/pointnet#13]
I trained with also 15 epochs 
then I modify the save_14.pth to get into the evaluation and I got this confusion matrix  completely bias with the monitor
![image](https://user-images.githubusercontent.com/11828200/99622577-4c54be00-29df-11eb-953e-d338825a1e41.png). 

Is there any reason why? what would you recommend  me to do?! I am following you Colab https://colab.research.google.com/github/nikitakaraevv/pointnet/blob/master/nbs/PointNetClass.ipynb#scrollTo=y2i_0ECIcR1X

**Comment by nikitakaraevv** [comment]
Hi @albertotono,

Thank for your interest and for your feedback!
I've just reran the [PointNetClass](https://github.com/nikitakaraevv/pointnet/blob/master/nbs/PointNetClass.ipynb) notebook. I trained PointNet for 3 epochs and this is the confusion matrix I obtained: 
<img width="616" alt="Screenshot 2020-11-22 at 13 51 10" src="https://user-images.githubusercontent.com/37815420/99901890-fdeb3c00-2cca-11eb-9f18-e5155fcf8114.png">

Maybe there was something different in your settings. By the way, I've just committed a new version of this notebook in case there was an error in there. Check it out and let me know if it worked for you!

Thanks, Nikita

**Comment by albertotono** [comment]
Thank you so much to you Nikita, much appreciate your quick answer. 

Awesome now it is working great also with 2 epochs, 
1. may I ask you what did you change?
![image](https://user-images.githubusercontent.com/11828200/99916743-c4adce80-2cc0-11eb-8f45-5dd57428b6cf.png)



On your **colab** code you had this 
```
 File "<ipython-input-44-346c143f8d34>", line 38
    torch.save(pointnet.state_dict(), "save_"+str(epoch)".pth")
                                                             ^
SyntaxError: invalid syntax
```
So I changed to this 
```
 # save the model
        if save:
            torch.save(pointnet.state_dict(), "save_"+str(epoch)+".pth")
```
Then I trained with 2 epochs as well. ( around 1hours with Colab GPU)
and also I add `save=True`

[Epoch: 2, Batch:   70 /  125], loss: 0.556
This is during my training, it appears with **125**.

Then when I evaluate it goes like this
Batch [   3 /   **15**]

2.  Can you help me understanding the different between **125 and 15** what are those numbers?

We have
Train dataset size:  3991
Valid dataset size:  908

Thanks you so much
