### ISSUE TITLE
Advice: Using `x, y, z` points stored in CSV

### ISSUE THREAD

**Issue by shrutirao94** [nikitakaraevv/pointnet#6]
Hello! Thank you for sharing this implementation of PointNet! I found your tutorial super clear and easy to follow through! I am currently working on neutrino vs background classification for my masters research and the team requires me to use PointCloud NN. I was unsure about how my data format would fit this NN implementation.

The dataset (around 5GB) has x, y, z positions and a label indicating whether it is a neutrino or background in csv format.  I can group the neutrinos into muon events that will represent point clouds.

```
dom_id,  pos_x ,pos_y, pos_z, dir_x ,dir_y, dir_z, tot, time, label
321.0,  -17.660999999999994, 32.245,65.23100000000001, -0.46, -0.266, -0.847, 26.0, 0.0, 0

```
I am unsure if my data will work here since it is just plain x, y, z points and does not have meshes (like in the example used). Is it possible to use this data and format with the implementation? The pointnet paper does mention that simple x,y,z coordinates can be used at the very least but I'm not very confident. Any advice would be quite appreciated!

**Comment by nikitakaraevv** [comment]
Hello @shrutirao94! 
Thank you for your feedback and for the question.
Actually, if we have point clouds where points are uniformly (or roughly uniformly) distributed on a surface in 3D-space, we can use just this data to train our PointNet! 

In this case, we don't really need information about connectivity (meshes) to resample point clouds. So, we could pass the original point clouds to the network directly which you could definitely do in your project :)

Hope that this was helpful.

**Comment by shrutirao94** [comment]
Hey @nikitakaraevv thanks for your reply and help! I will definitely look into doing that then and see how it goes!

Thanks once again!

**Comment by AtrCheema** [comment]
I have a general question related to x,y,z points. Can we use pointnet for meshes where the distances between nodes are not uniform and the distances are actually important e.g. in crystal structure classification?
